[package]
name = "hello-world"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
rustapi-core = { path = "../../crates/rustapi-core" }
rustapi-openapi = { path = "../../crates/rustapi-openapi" }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
