[workspace]
resolver = "2"
members = [
    "crates/rustapi-core",
    "crates/rustapi-openapi",
    "examples/hello-world",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Simone Romano"]
repository = "https://github.com/simoneromano96/rustapi"

[workspace.dependencies]
monoio = { version = "0.2", features = ["sync", "poll-io"] }
httparse = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-graphql = "7"
utoipa = "5"
thiserror = "1"
